# Generated by Django 5.2.1 on 2026-06-25 19:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полное название отдела или подразделения.', max_length=150, unique=True, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, default='', help_text='Краткое описание задач и зоны ответственности отдела.', verbose_name='Описание')),
                ('email', models.EmailField(blank=True, default='', help_text='Общий почтовый адрес отдела.', max_length=254, verbose_name='Контактный e-mail')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите флаг, чтобы скрыть отдел из выбора.', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Латинский идентификатор для URL (заполняется автоматически).', max_length=150, unique=True, verbose_name='URL-псевдоним')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория тикета',
                'verbose_name_plural': 'Категории тикетов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название приоритета')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-псевдоним')),
                ('color', models.CharField(default='#6c757d', help_text='Цвет для визуального выделения приоритета.', max_length=7, verbose_name='Цвет (HEX)')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Чем выше число, тем выше приоритет.', unique=True, verbose_name='Числовой уровень')),
            ],
            options={
                'verbose_name': 'Приоритет тикета',
                'verbose_name_plural': 'Приоритеты тикетов',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название статуса')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-псевдоним')),
                ('color', models.CharField(default='#6c757d', help_text='Цвет для отображения статуса в интерфейсе, например #28a745.', max_length=7, verbose_name='Цвет (HEX)')),
                ('is_closed', models.BooleanField(default=False, help_text='Отметьте, если данный статус означает завершение работы над тикетом.', verbose_name='Является закрывающим')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус тикета',
                'verbose_name_plural': 'Статусы тикетов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CLIENT', 'Клиент'), ('SUPPORT', 'Саппорт'), ('ADMIN', 'Администратор')], default='CLIENT', help_text='Роль определяет уровень доступа пользователя в системе.', max_length=10, verbose_name='Роль')),
                ('patronymic', models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, default='', help_text='Контактный номер телефона.', max_length=20, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, help_text='Фотография профиля пользователя.', null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, default='', help_text='Краткая информация о пользователе.', verbose_name='О себе')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, help_text='Отдел, к которому прикреплён сотрудник.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='helpdesk.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя отправителя (для неавторизованных).', max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Адрес для обратной связи.', max_length=254, verbose_name='E-mail')),
                ('subject', models.CharField(max_length=300, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_processed', models.BooleanField(default=False, help_text='Отметьте, когда обращение будет рассмотрено.', verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(blank=True, help_text='Заполняется автоматически для авторизованных пользователей.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение (обратная связь)',
                'verbose_name_plural': 'Обращения (обратная связь)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Кратко опишите суть проблемы или вопроса.', max_length=300, verbose_name='Тема обращения')),
                ('description', models.TextField(help_text='Подробное описание обращения.', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('assignee', models.ForeignKey(blank=True, help_text='Сотрудник поддержки, назначенный на обработку тикета.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('author', models.ForeignKey(help_text='Пользователь, создавший тикет.', on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='helpdesk.department', verbose_name='Отдел-исполнитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.ticketcategory', verbose_name='Категория')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.ticketpriority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.ticketstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_internal', models.BooleanField(default=False, help_text='Внутренние комментарии видны только сотрудникам поддержки.', verbose_name='Внутренний комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.ticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(help_text='Исходное имя файла при загрузке.', max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('comment', models.ForeignKey(blank=True, help_text='Если файл приложен к конкретному комментарию.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.comment', verbose_name='Комментарий')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.ticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TICKET_CREATED', 'Тикет создан'), ('TICKET_UPDATED', 'Тикет обновлён'), ('TICKET_CLOSED', 'Тикет закрыт'), ('STATUS_CHANGED', 'Статус изменён'), ('ASSIGNEE_CHANGED', 'Исполнитель назначен'), ('COMMENT_ADDED', 'Комментарий добавлен'), ('FILE_UPLOADED', 'Файл загружен'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип действия')),
                ('description', models.TextField(blank=True, default='', help_text='Подробное описание выполненного действия.', verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='helpdesk.ticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='URL-псевдоним')),
                ('content', models.TextField(help_text='Полный текст статьи. Поддерживается форматирование Markdown.', verbose_name='Содержание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kb_articles', to='helpdesk.ticketcategory', verbose_name='Основная категория')),
                ('tags', models.ManyToManyField(blank=True, help_text='Дополнительные категории для перекрёстной навигации.', related_name='tagged_kb_articles', to='helpdesk.ticketcategory', verbose_name='Теги (категории)')),
            ],
            options={
                'verbose_name': 'Статья базы знаний',
                'verbose_name_plural': 'Статьи базы знаний',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, help_text='Категория, к которой относится вопрос.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_articles', to='helpdesk.ticketcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья FAQ',
                'verbose_name_plural': 'Статьи FAQ',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
